name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
homepage: https://firebase.google.com/docs/auth
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth
version: 3.3.20
publish_to: "none"

false_secrets:
  - example/**

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_auth_platform_interface: ^6.2.8
  firebase_core:
    git:
      url: git@github.com-mine:amanxnanda/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@github.com-mine:amanxnanda/flutterfire.git
      path: packages/firebase_auth/firebase_core_platform_interface
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.auth
        pluginClass: FlutterFirebaseAuthPlugin
      ios:
        pluginClass: FLTFirebaseAuthPlugin
      macos:
        pluginClass: FLTFirebaseAuthPlugin
      web:
        default_package: firebase_auth_web
